### ISSUE TITLE
Improvement : Fast commit

### ISSUE THREAD

**Issue by 4sStylZ** [sgolemon/git#1]
Hi,

I have this alias suggestion,

`alias fastcommit='git commit -a -m "$(curl -s http://whatthecommit.com/index.txt)"'`

Or this one but, don’t take it too seriously : 

`alias gitlog='git log --graph --pretty=format:'\''%C(red)%h%Creset -%C(yellow)%d%Creset %s %C(green)(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit'`

**Comment by sgolemon** [comment]
I'll give these a go, but my config needs desperate updating in general... :/

**Comment by 4sStylZ** [comment]
No problem, it’s a joke.
